name: spannable_grid
description: Custom grid widget that allows it's cells to span columns and rows and supports editing.
version: 0.3.0
homepage: https://github.com/ech89899/spannablegrid-flutter
repository: https://github.com/ech89899/spannablegrid-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
